---
title: "Brainstorm"
format: gfm
---

This document is an accumulator for notes that have nowhere else to go. Partially finished thoughts, flashes of inspiration, etc.

# Ideas

[`2022-11-17`]{.aside}

## Participant Pathways

- A participant pathway is a chain of events that a participant experiences.
- It begins at the start of their involvement with the program, and ends at the conclusion of the follow-up period.
- Each pathway is made up of Milestones, events that we care about, which have some decisive affect on the course of a given participant's pathway.
- Care should be taken at the outset of an evaluation project to clearly and specifically define the universe of pathways we want to investigate.

## FairWeather: A Hypothetical Case Study

Consider a hypothetical program called FairWeather, which offers an on-ramp to a career in the green energy manufacuring industry to NEET youth under 30 in three stages.
FairWeather is delivered by a non-profit service provider called CanWork.
CanWork maintains relationships with industry professionals in various roles who have volunteered to work with participants in the Job Shadowing aspects of the program.

Each of the volunteers has one of the following roles:

- Millwright
- Assembly line worker
- Industrial designer
- Manager

1. Career Exploration: In the first -- and only mandatory -- stage of the FairWeather program, participants spend three weeks in a classroom setting learning about themselves, the green energy manufacturing labour market, and the opportunities that may be a good fit for them.
2. Job Shadowing: In the second phase, participants select the two roles (from the four volunteer role categories) in which they have the most interest as potential careers.
For each of their selections, they are assigned a volunteer with that role, whom they spend two weeks shadowing.
3. Coaching and Mentoring: Following the job shadowing stage, participants are given the opportunity to discuss their experience with a career coach, with whom they collaboratively develop a plan to establish the participant in their career of interest.
The participant's progress on that plan is monitored by the Coach, who remains in contact and available to the participant.

FairWeather is funded by Nova Onbertoba Works!, which administers the LMDA in Nova Onbertoba, a completely made up province in Canada. Assume Nova Onbertoba Works! (NOW) functions roughly equivalently to Employment Ontario (EO). NOW's funding is contingent on enrollment, which CanWork expects to range between 350 and 500 over the projected two year lifespan of the pilot.

### How do Participants enroll in FairWeather?

Participants can independently enroll in FairWeather, either in-person at one of CanWork's brick-and-mortar locations, or online through CanWork's participant portal. Enrollment can also be initiated by a referral from the participant's social assistance caseworker, or a counsellor at one of CanWork's referral partners.

### What is CanWork trying to do?

For FairWeather, NOW has imposed targets for post-treatment outcomes, and for the representation of key demographic groups within the participant population.

#### Process Targets

- 400 participants enrolled
- 80% graduation rate
- 90% satisfaction rate among graduates

#### Outcome Targets

- 200 FairWeather graduates either in relevant formal training or employed in the target industry
- 50% of remaining FairWeather graduates either employed or in formal training

## Test-Driven Development

Is standard practice in other areas of software engineering.
Adopting a test-driven development paradigm for our analysis projects would represent a shift to taking seriously the idea that we're building software for analysis.
Starting with tests forces reasoning explicitly and clearly about expectations.